### ISSUE TITLE
Fix typo when accessing nodes

### ISSUE THREAD

**Issue by achabotl** [Zettelkasten-Method/zkviz#21]
Bug from [forum](https://forum.zettelkasten.de/discussion/comment/3610/#Comment_3610)

```
Traceback (most recent call last):
File "/Users/tdiaz/envs/zkviz/bin/zkviz", line 11, in 
load_entry_point('zkviz==1.3.0', 'console_scripts', 'zkviz')()
File "/Users/tdiaz/envs/zkviz/lib/python3.7/site-packages/zkviz/zkviz.py", line 197, in main
graph.render(args.output)
File "/Users/tdiaz/envs/zkviz/lib/python3.7/site-packages/zkviz/plotly.py", line 158, in render
fig = self.build_plotly_figure()
File "/Users/tdiaz/envs/zkviz/lib/python3.7/site-packages/zkviz/plotly.py", line 98, in build_plotly_figure
text = "
".join([node, self.graph.node[node].get("title", "")])
AttributeError: 'Graph' object has no attribute 'node'
```

It should be `self.graph.nodes` with an S.

**Comment by DivineDominion** [comment]
fixed in #20
