### ISSUE TITLE
Script does not find any files

### ISSUE THREAD

**Issue by ghost** [Zettelkasten-Method/zkviz#22]
I am trying to run this on both .md files and .wiki files (with the --pattern option) and even if I specify the directory, the script always returns:

```
no@x60:~/envs/zkviz/bin$ ~/envs/zkviz/bin/zkviz --only-list --notes-dir "/home/no/try/vimwiki/LT/Ab1.md" "/home/no/try/vimwiki/LT/Ab2.md" --only-list
Traceback (most recent call last):
  File "/home/no/envs/zkviz/bin/zkviz", line 11, in <module>
    load_entry_point('zkviz==1.3.0', 'console_scripts', 'zkviz')()
  File "/home/no/envs/zkviz/lib/python3.6/site-packages/zkviz/zkviz.py", line 168, in main
    raise FileNotFoundError("I'm sorry, I couldn't find any files.")
FileNotFoundError: I'm sorry, I couldn't find any files.
```

Am I missing something obvious here? I have all graphviz packages installed from what I can tell and even with --only-list, as above, it does not work.

**Comment by DivineDominion** [comment]
I think the `--notes-dir` argument should be preceded by a directory path for file globbing, while you supply a _file_ path; does this work?

```
$ ~/envs/zkviz/bin/zkviz --only-list --notes-dir "/home/no/try/vimwiki/LT" --only-list
```

**Comment by ghost** [comment]
Thanks for the reply, but unfortunately your suggestion does not work either.

**Comment by bcdavasconcelos** [comment]
Same problem over here.

```
~/envs/zkviz/bin/zkviz --only-list --notes-dir "~/Dropbox/001\ Megawiki/Zettelkasten" --only-list
Traceback (most recent call last):
  File "/Users/bernardovasconcelos/envs/zkviz/bin/zkviz", line 11, in <module>
    load_entry_point('zkviz==1.3.0', 'console_scripts', 'zkviz')()
  File "/Users/bernardovasconcelos/envs/zkviz/lib/python3.8/site-packages/zkviz/zkviz.py", line 168, in main
    raise FileNotFoundError("I'm sorry, I couldn't find any files.")
FileNotFoundError: I'm sorry, I couldn't find any files.
```

**Comment by bcdavasconcelos** [comment]
My mistake. I didn't notice that the script was expecting a zettel id in the format yyyyMMdd before the file.
